### PR TITLE
Fix the chrome settings crash

### PR DESCRIPTION
**Pull request by LeFroid**
After testing the patch submitted at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=200601 
the crash related to the settings page is fixed. Besides this, I tested the other PR that was recently submitted to you for the tab crashes and would recommend that their patch is added to the chromium port as well (builds with no issues and I haven't experienced a tab crash yet).

### CODE REVIEW

**Comment by teran-mckinney** [comment]
Hi LeFroid,

Thank you so much for working on this. In #14 we have a bit of discussion on this and I noted that #19 fixes this. Do you think some parts of this should still be merged?

So far, chrome://settings is fine for me. I'll keep using it and see if I get any more crashes.

Sincerely,
Teran

**Comment by teran-mckinney** [comment]
@rene0 what do you think about this? I'm still seeing lots of crashes even after #19 was merged in.

Thank you!

**Comment by LeFroid** [comment]
There are a few other patches in my PR from the port to OpenBSD that aren't included in pr #19 , which may or may not increase overall stability. Their team seems to pretty good at what they do

The only issue, however, is that while I haven't experienced any browser crashes on my branch, there are seemingly random triggers that cause kernel panics (at least on 10-stable, amd64)

Have you experienced such an issue as of yet?
I'm not near my computer at the moment but remember that the panic log said something about a dup_alloc and/or var_alloc

**Comment by teran-mckinney** [comment]
Hi @LeFroid,

I haven't tested your patches yet, but I have not had a single FreeBSD kernel panic, ever. I'm using Chrome on my laptop about 40 hours a week. Usually two of them, under two different users. This is on a Thinkpad X230 with 10.1-RELEASE.

Were you seeing those even before the patches? I wonder if it's a hardware issue or a 10-STABLE issue.

**Comment by ivadasz** [comment]
@teran-mckinney can you give a hint on which web-pages you are still seeing crashes?
@teran-mckinney Also, how does chromium crash for yuo? With just an Aw Snap! tab, or does the complete chromium program stop?

**Comment by ivadasz** [comment]
@LeFroid You should definitely clean up the history of your branch. Best start with a new branch from the current master of the gliaskos/freebsd-chromium repository and cherry-pick the relevant parts of your current branch.
Currently it's not easily visible what the changes are relative to the current master of gliaskos/freebsd-chromium, and it's unnecessarily difficult to test or review.

**Comment by teran-mckinney** [comment]
@ivadasz I see this on all sorts of web pages, but I think generally those with some kind of common cookie or authentication. Sometimes, one will crash with others at the same time. I've seen this on: Hipchat, Jira, Github, Okta, for a short list. It's just the Aw, Snap! page. Never a crash except prior with the settings page, which is now fixed.

**Comment by LeFroid** [comment]
@ivadasz I created a new branch for that purpose and am currently picking all the patches that I feel are relevant for a PR. In doing so I will now close this PR

**Pull request closed without merging**
