### PR TITLE
Update to 71.0.3578.98

### PR DESCRIPTION
**Pull request by mwolf-rw**
Updated port & patches to work with the latest Chromium stable (71.0.3578.98).

### CODE REVIEW

**Comment by rene0** [comment]
One quick note: the main Makefile got stale, you can leave out the FreeBSD version < 11 block entirely now.

**Comment by mwolf-rw** [comment]
Thanks! Let me know if I can improve something.

**Comment by cpu82** [comment]
I've created a new pull request.

Thanks @mwolf-rw

**Comment by rene0** [comment]
So #134 overrules this request?

**Comment by cpu82** [comment]
> So #134 overrules this request?

Only merge #134

**Comment by rene0** [comment]
Superseded by #134

**Pull request closed without merging**
